### ISSUE TITLE
Point to transpiled version

### ISSUE THREAD

**Issue by caisah** [ndaidong/bella-scheduler#13]
Hi, 

A package I use, uses in turn your package. Currently in `index.js` you have:
```javascript
exports = module.exports = require('./src/main');
```

Could you please point to the transpiled version like this?
```javascript
exports = module.exports = require('./dist/scheduler');
```

I use `webpack` with `uglifyJS` plugin and I have problems on build, because the `src` module is not transpiled to ES5 (I don't want to add all sorts of rules to my `webpack` file). This will also keep compatibility with older browsers.

Thanks!

**Comment by ndaidong** [comment]
Thanks for your nice suggestion, sorry for late reply.
