### ISSUE TITLE
Is there any option to remove listener ?

### ISSUE THREAD

**Issue by argjendhaxhiu** [ndaidong/bella-scheduler#9]
I'm adding a schedule for users to change their status and is working very well but what if I want to update or delete that schedule how can I terminate the previous listener in order to not happened. 

Thanks

**Comment by ndaidong** [comment]
Thank you for your question. Currently no. I will implement this feature for next version.

**Comment by ndaidong** [comment]
SInce v1.1.4, you can remove task by using unregister() method. For example:

```
let taskId = scheduler.once('wed 15', callback);
scheduler.unregister(taskId); 
```
